### ISSUE TITLE
Add debug option for notifications

### ISSUE THREAD

**Issue by jrnhrmn** [LAB02-Admin/HASS.Agent-Docs#1]
https://hassagent.readthedocs.io/en/latest/notifications/notification-debugging-client-side/

If somebody would use focus assist in WIndows they should add HAss.Agent to the priority list.

**Comment by LAB02-Admin** [comment]
Done:

![image](https://user-images.githubusercontent.com/81011038/177935970-8fae0737-0813-4ab8-a493-c7f9319ecf23.png)

Thanks @jrnhrmn!
